version: "3.1"

services:
  db:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rest-api
    ports:
      - "5432:5432"
